using Blazored.Toast;
using Ecommerce.Web.Client;
using Ecommerce.Web.Client.Services;
using Ecommerce.Web.Client.Services.AppSettings;
using Ecommerce.Web.Client.Services.Carts;
using Ecommerce.Web.Client.Services.Categories;
using Ecommerce.Web.Client.Services.Products;
using Ecommerce.Web.Client.Services.Users;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.Services.AddSingleton(sp => new HttpClient { BaseAddress = new Uri("https://localhost:7290") });
builder.Services.AddSingleton<IApiService,ApiService>();
builder.Services.AddScoped<IProductService, ProductService>();
builder.Services.AddScoped<ICategoryService, CategoryService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IAppSettingsService, AppSettingsService>();
builder.Services.AddSingleton<ICartServices, CartServices>();
builder.Services.AddSingleton<AppState>();
builder.Services.AddBlazoredToast();
builder.Services.AddAuthorizationCore();
builder.Services.AddCascadingAuthenticationState();
builder.Services.AddSingleton<AuthenticationStateProvider,PersistentAuthenticationStateProvider>();
await builder.Build().RunAsync();
